package com.xianguo.pojo;

// Generated 2016-12-7 18:09:26 by Hibernate Tools 3.4.0.CR1

/**
 * OrdersProductId generated by hbm2java
 */
public class OrdersProductId implements java.io.Serializable {

	private Long oid;
	private Long pid;
	private Long opnumber;

	public OrdersProductId() {
	}

	public OrdersProductId(Long oid, Long pid, Long opnumber) {
		this.oid = oid;
		this.pid = pid;
		this.opnumber = opnumber;
	}

	public Long getOid() {
		return this.oid;
	}

	public void setOid(Long oid) {
		this.oid = oid;
	}

	public Long getPid() {
		return this.pid;
	}

	public void setPid(Long pid) {
		this.pid = pid;
	}

	public Long getOpnumber() {
		return this.opnumber;
	}

	public void setOpnumber(Long opnumber) {
		this.opnumber = opnumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrdersProductId))
			return false;
		OrdersProductId castOther = (OrdersProductId) other;

		return ((this.getOid() == castOther.getOid()) || (this.getOid() != null
				&& castOther.getOid() != null && this.getOid().equals(
				castOther.getOid())))
				&& ((this.getPid() == castOther.getPid()) || (this.getPid() != null
						&& castOther.getPid() != null && this.getPid().equals(
						castOther.getPid())))
				&& ((this.getOpnumber() == castOther.getOpnumber()) || (this
						.getOpnumber() != null
						&& castOther.getOpnumber() != null && this
						.getOpnumber().equals(castOther.getOpnumber())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getOid() == null ? 0 : this.getOid().hashCode());
		result = 37 * result
				+ (getPid() == null ? 0 : this.getPid().hashCode());
		result = 37 * result
				+ (getOpnumber() == null ? 0 : this.getOpnumber().hashCode());
		return result;
	}

}
