package com.xianguo.pojo;

// Generated 2016-12-7 18:09:26 by Hibernate Tools 3.4.0.CR1

/**
 * OrdersProduct generated by hbm2java
 */
public class OrdersProduct implements java.io.Serializable {

	private OrdersProductId id;
	private Product product;
	private Orders orders;

	public OrdersProduct() {
	}

	public OrdersProduct(OrdersProductId id) {
		this.id = id;
	}

	public OrdersProduct(OrdersProductId id, Product product, Orders orders) {
		this.id = id;
		this.product = product;
		this.orders = orders;
	}

	public OrdersProductId getId() {
		return this.id;
	}

	public void setId(OrdersProductId id) {
		this.id = id;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

}
