package com.xianguo.pojo;

// Generated 2016-12-7 18:09:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private Long oid;
	private Customer customer;
	private String ocontact;
	private String ophone;
	private String oaddress;
	private String opay;
	private Date ocreateDate;
	private Long ostatus;
	private Set<OrdersProduct> ordersProducts = new HashSet<OrdersProduct>(0);

	public Orders() {
	}

	public Orders(Customer customer) {
		this.customer = customer;
	}

	public Orders(Customer customer, String ocontact, String ophone,
			String oaddress, String opay, Date ocreateDate, Long ostatus,
			Set<OrdersProduct> ordersProducts) {
		this.customer = customer;
		this.ocontact = ocontact;
		this.ophone = ophone;
		this.oaddress = oaddress;
		this.opay = opay;
		this.ocreateDate = ocreateDate;
		this.ostatus = ostatus;
		this.ordersProducts = ordersProducts;
	}

	public Long getOid() {
		return this.oid;
	}

	public void setOid(Long oid) {
		this.oid = oid;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getOcontact() {
		return this.ocontact;
	}

	public void setOcontact(String ocontact) {
		this.ocontact = ocontact;
	}

	public String getOphone() {
		return this.ophone;
	}

	public void setOphone(String ophone) {
		this.ophone = ophone;
	}

	public String getOaddress() {
		return this.oaddress;
	}

	public void setOaddress(String oaddress) {
		this.oaddress = oaddress;
	}

	public String getOpay() {
		return this.opay;
	}

	public void setOpay(String opay) {
		this.opay = opay;
	}

	public Date getOcreateDate() {
		return this.ocreateDate;
	}

	public void setOcreateDate(Date ocreateDate) {
		this.ocreateDate = ocreateDate;
	}

	public Long getOstatus() {
		return this.ostatus;
	}

	public void setOstatus(Long ostatus) {
		this.ostatus = ostatus;
	}

	public Set<OrdersProduct> getOrdersProducts() {
		return this.ordersProducts;
	}

	public void setOrdersProducts(Set<OrdersProduct> ordersProducts) {
		this.ordersProducts = ordersProducts;
	}

}
