package com.xianguo.pojo;

// Generated 2016-12-7 18:09:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Long pid;
	private Seller seller;
	private String pname;
	private String pcategory;
	private String pdescription;
	private String ppicLocation;
	private Long ptotalNumber;
	private Long pnumber;
	private Double pcostPrice;
	private Double psellingPrice;
	private String pproducePlace;
	private Date pupDate;
	private Long pinUp;
	private Set<OrdersProduct> ordersProducts = new HashSet<OrdersProduct>(0);

	public Product() {
	}

	public Product(Seller seller) {
		this.seller = seller;
	}

	public Product(Seller seller, String pname, String pcategory,
			String pdescription, String ppicLocation, Long ptotalNumber,
			Long pnumber, Double pcostPrice, Double psellingPrice,
			String pproducePlace, Date pupDate, Long pinUp,
			Set<OrdersProduct> ordersProducts) {
		this.seller = seller;
		this.pname = pname;
		this.pcategory = pcategory;
		this.pdescription = pdescription;
		this.ppicLocation = ppicLocation;
		this.ptotalNumber = ptotalNumber;
		this.pnumber = pnumber;
		this.pcostPrice = pcostPrice;
		this.psellingPrice = psellingPrice;
		this.pproducePlace = pproducePlace;
		this.pupDate = pupDate;
		this.pinUp = pinUp;
		this.ordersProducts = ordersProducts;
	}

	public Long getPid() {
		return this.pid;
	}

	public void setPid(Long pid) {
		this.pid = pid;
	}

	public Seller getSeller() {
		return this.seller;
	}

	public void setSeller(Seller seller) {
		this.seller = seller;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public String getPcategory() {
		return this.pcategory;
	}

	public void setPcategory(String pcategory) {
		this.pcategory = pcategory;
	}

	public String getPdescription() {
		return this.pdescription;
	}

	public void setPdescription(String pdescription) {
		this.pdescription = pdescription;
	}

	public String getPpicLocation() {
		return this.ppicLocation;
	}

	public void setPpicLocation(String ppicLocation) {
		this.ppicLocation = ppicLocation;
	}

	public Long getPtotalNumber() {
		return this.ptotalNumber;
	}

	public void setPtotalNumber(Long ptotalNumber) {
		this.ptotalNumber = ptotalNumber;
	}

	public Long getPnumber() {
		return this.pnumber;
	}

	public void setPnumber(Long pnumber) {
		this.pnumber = pnumber;
	}

	public Double getPcostPrice() {
		return this.pcostPrice;
	}

	public void setPcostPrice(Double pcostPrice) {
		this.pcostPrice = pcostPrice;
	}

	public Double getPsellingPrice() {
		return this.psellingPrice;
	}

	public void setPsellingPrice(Double psellingPrice) {
		this.psellingPrice = psellingPrice;
	}

	public String getPproducePlace() {
		return this.pproducePlace;
	}

	public void setPproducePlace(String pproducePlace) {
		this.pproducePlace = pproducePlace;
	}

	public Date getPupDate() {
		return this.pupDate;
	}

	public void setPupDate(Date pupDate) {
		this.pupDate = pupDate;
	}

	public Long getPinUp() {
		return this.pinUp;
	}

	public void setPinUp(Long pinUp) {
		this.pinUp = pinUp;
	}

	public Set<OrdersProduct> getOrdersProducts() {
		return this.ordersProducts;
	}

	public void setOrdersProducts(Set<OrdersProduct> ordersProducts) {
		this.ordersProducts = ordersProducts;
	}

}
