package com.xianguo.pojo;

// Generated 2016-12-7 18:09:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Seller generated by hbm2java
 */
public class Seller implements java.io.Serializable {

	private Long sid;
	private String susername;
	private String spwd;
	private String spwdProtection;
	private String spwdAnswer;
	private String sshopName;
	private String sphone;
	private String smail;
	private String saddress;
	private Date sregistrationDate;
	private Long sinUse;
	private Set<Product> products = new HashSet<Product>(0);

	public Seller() {
	}

	public Seller(String susername, String spwd, String spwdProtection,
			String spwdAnswer, String sshopName, String sphone, String smail,
			String saddress, Date sregistrationDate, Long sinUse,
			Set<Product> products) {
		this.susername = susername;
		this.spwd = spwd;
		this.spwdProtection = spwdProtection;
		this.spwdAnswer = spwdAnswer;
		this.sshopName = sshopName;
		this.sphone = sphone;
		this.smail = smail;
		this.saddress = saddress;
		this.sregistrationDate = sregistrationDate;
		this.sinUse = sinUse;
		this.products = products;
	}

	public Long getSid() {
		return this.sid;
	}

	public void setSid(Long sid) {
		this.sid = sid;
	}

	public String getSusername() {
		return this.susername;
	}

	public void setSusername(String susername) {
		this.susername = susername;
	}

	public String getSpwd() {
		return this.spwd;
	}

	public void setSpwd(String spwd) {
		this.spwd = spwd;
	}

	public String getSpwdProtection() {
		return this.spwdProtection;
	}

	public void setSpwdProtection(String spwdProtection) {
		this.spwdProtection = spwdProtection;
	}

	public String getSpwdAnswer() {
		return this.spwdAnswer;
	}

	public void setSpwdAnswer(String spwdAnswer) {
		this.spwdAnswer = spwdAnswer;
	}

	public String getSshopName() {
		return this.sshopName;
	}

	public void setSshopName(String sshopName) {
		this.sshopName = sshopName;
	}

	public String getSphone() {
		return this.sphone;
	}

	public void setSphone(String sphone) {
		this.sphone = sphone;
	}

	public String getSmail() {
		return this.smail;
	}

	public void setSmail(String smail) {
		this.smail = smail;
	}

	public String getSaddress() {
		return this.saddress;
	}

	public void setSaddress(String saddress) {
		this.saddress = saddress;
	}

	public Date getSregistrationDate() {
		return this.sregistrationDate;
	}

	public void setSregistrationDate(Date sregistrationDate) {
		this.sregistrationDate = sregistrationDate;
	}

	public Long getSinUse() {
		return this.sinUse;
	}

	public void setSinUse(Long sinUse) {
		this.sinUse = sinUse;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
